### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by pragdave** [Renovamen/vuepress-theme-gungnir#64]
### ✅ Checklist

- [X] I am using the **latest version**

#### Concise Description

The following input:

~~~ markdown
---
title: Test
---

$\sqrt{x}$
~~~

Generates the following error:

~~~
ParseError: KaTeX parse error: Expected group as argument to '\sqrt' at end of input: \sqrt
    at new ParseError (/Volumes/X8/LevelUp/Content/node_modules/katex/dist/katex.js:100:14)
    at Parser.parseGroupOfType (/Volumes/X8/LevelUp/Content/node_modules/katex/dist/katex.js:17918:19)
    at Parser.parseArguments (/Volumes/X8/LevelUp/Content/node_modules/katex/dist/katex.js:17848:22)
    at Parser.parseFunction (/Volumes/X8/LevelUp/Content/node_modules/katex/dist/katex.js:17794:37)
    at Parser.parseGroup (/Volumes/X8/LevelUp/Content/node_modules/katex/dist/katex.js:18190:21)
    at Parser.parseAtom (/Volumes/X8/LevelUp/Content/node_modules/katex/dist/katex.js:17629:21)
    at Parser.parseExpression (/Volumes/X8/LevelUp/Content/node_modules/katex/dist/katex.js:17491:23)
    at Parser.parse (/Volumes/X8/LevelUp/Content/node_modules/katex/dist/katex.js:17423:24)
    at parseTree (/Volumes/X8/LevelUp/Content/node_modules/katex/dist/katex.js:18431:21)
    at renderToDomTree (/Volumes/X8/LevelUp/Content/node_modules/katex/dist/katex.js:18540:16) {
  position: 5
}
~~~

Something similar happens whenever an open brace appears in KaTeX input: $123_{10}$ etc.

Thanks for all your work.

Dave

### 📄 Environment info (`npx vuepress info`)

~~~ yaml
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 293.32 MB / 16.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
Binaries:
    Node: 16.4.1 - ~/.asdf/installs/nodejs/16.4.1/bin/node
    Yarn: 1.22.17 - ~/.asdf/installs/nodejs/16.4.1/.npm/bin/yarn
    npm: 7.18.1 - ~/.asdf/plugins/nodejs/shims/npm
Utilities:
    Git: 2.32.0 - /usr/bin/git
Browsers:
    Chrome: 101.0.4951.64
    Edge: 101.0.1210.53
    Firefox: 100.0.1
    Safari: 15.4
npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.45 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.45 
    @vuepress/client:  2.0.0-beta.45 
    @vuepress/core:  2.0.0-beta.45 
    @vuepress/markdown:  2.0.0-beta.45 
    @vuepress/plugin-active-header-links:  2.0.0-beta.45 
    @vuepress/plugin-back-to-top:  2.0.0-beta.45 
    @vuepress/plugin-container: ^2.0.0-beta.39 => 2.0.0-beta.45 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.45 
    @vuepress/plugin-git:  2.0.0-beta.45 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.45 
    @vuepress/plugin-nprogress:  2.0.0-beta.45 
    @vuepress/plugin-palette:  2.0.0-beta.45 
    @vuepress/plugin-prismjs:  2.0.0-beta.45 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: ^2.0.0-beta.39 => 2.0.0-beta.45 
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.45 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.45 
    @vuepress/theme-default:  2.0.0-beta.45 
    @vuepress/utils:  2.0.0-beta.45 
    vue:  3.2.35 
    vue-loader: Not Found
    vue-router:  4.0.15 
    vuepress: ^2.0.0-beta.39 => 2.0.0-beta.45 
    vuepress-vite:  2.0.0-beta.45 
    vuepress-webpack: Not Found
~~~

**Comment by Renovamen** [comment]
Hi, it works fine for me, could you please provide a minimal reproduction? Thanks!
