### ISSUE TITLE
[Bug report] npm run docs:build error

### ISSUE THREAD

**Issue by codebirdlong** [Renovamen/vuepress-theme-gungnir#79]
### ✅ Checklist

- [X] I am using the **latest version**

#### Concise Description
I run `npm run docs:build` has a error, please!

TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.removeLeadingSlash (/www/docker-hub/vuepress/vuepress-blog-gungnir/node_modules/@vuepress/shared/dist/index.cjs:154:39)
    at withBase (/www/docker-hub/vuepress/vuepress-blog-gungnir/docs/.vuepress/.temp/.server/app.js:316:27)
    at /www/docker-hub/vuepress/vuepress-blog-gungnir/docs/.vuepress/.temp/.server/app.js:5810:188
    at renderComponentSubTree (/www/docker-hub/vuepress/vuepress-blog-gungnir/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:250:13)
    at renderComponentVNode (/www/docker-hub/vuepress/vuepress-blog-gungnir/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
    at Object.ssrRenderComponent (/www/docker-hub/vuepress/vuepress-blog-gungnir/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:605:12)
    at /www/docker-hub/vuepress/vuepress-blog-gungnir/docs/.vuepress/.temp/.server/app.js:5874:30
    at Object.ssrRenderList (/www/docker-hub/vuepress/vuepress-blog-gungnir/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:671:13)
    at /www/docker-hub/vuepress/vuepress-blog-gungnir/docs/.vuepress/.temp/.server/app.js:5873:22
    at renderComponentSubTree (/www/docker-hub/vuepress/vuepress-blog-gungnir/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:250:13)
### 📄 Environment info (`npx vuepress info`)

```shell

  System:
    OS: Linux 4.18 CentOS Linux 8
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6161 CPU @ 2.20GHz
    Memory: 5.91 GB / 7.59 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 17.8.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.12.2 - /usr/local/bin/npm
  Utilities:
    Git: 2.27.0 - /usr/bin/git
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.48
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.48
    @vuepress/client:  2.0.0-beta.48
    @vuepress/core:  2.0.0-beta.48
    @vuepress/markdown:  2.0.0-beta.48
    @vuepress/plugin-active-header-links:  2.0.0-beta.48
    @vuepress/plugin-back-to-top:  2.0.0-beta.48
    @vuepress/plugin-container:  2.0.0-beta.48
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.48
    @vuepress/plugin-git:  2.0.0-beta.48
    @vuepress/plugin-google-analytics:  2.0.0-beta.48
    @vuepress/plugin-medium-zoom:  2.0.0-beta.48
    @vuepress/plugin-nprogress:  2.0.0-beta.48
    @vuepress/plugin-palette:  2.0.0-beta.48
    @vuepress/plugin-prismjs:  2.0.0-beta.48
    @vuepress/plugin-pwa:  2.0.0-beta.48
    @vuepress/plugin-pwa-popup:  2.0.0-beta.48
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.48
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.48
    @vuepress/theme-default:  2.0.0-beta.48
    @vuepress/utils:  2.0.0-beta.48
    vue:  3.2.37
    vue-loader: Not Found
    vue-router:  4.0.16
    vuepress: ^2.0.0-beta.48 => 2.0.0-beta.48
    vuepress-vite:  2.0.0-beta.48
    vuepress-webpack: Not Found
```

**Comment by codebirdlong** [comment]
Maybe my markdown file is wrong
